<div style="border: 1px solid black">
<b><center><font size="4">Data Science</font></center></b>

<b><center><font size="3">Manipulation and Numerical Data Analysis with Numpy</font></center></b>

<b><center><font size="2">4 - Inspect</font></center></b>
</div>

**Notebook Developed by**: [Ricardo Campos](https://www.di.ubi.pt/~rcampos)<br>
**email:**  ricardo.campos@ubi.pt<br>
**Affiliation:** *Assistant Professor* @ [University of Beira Interior](http://www.ubi.pt);
*Researcher* @ [LIAAD](https://www.inesctec.pt/en/centres/liaad)-[INESC TEC](https://www.inesctec.pt/en)

<hr>

<p><a href="4Inspect.ipynb" title="Download Notebook" download><img src="https://www.di.ubi.pt/~rcampos/assets/img_tutorials/download.jpg" align = "left" width="50" height="50" alt="Download Notebook"></a></p>
<p>&nbsp;</p>
<p>&nbsp;</p>

<hr>

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Basic-Information" data-toc-modified-id="Basic-Information-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Basic Information</a></span><ul class="toc-item"><li><span><a href="#ndarray-structure" data-toc-modified-id="ndarray-structure-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>ndarray structure</a></span></li><li><span><a href="#array-type" data-toc-modified-id="array-type-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>array type</a></span></li><li><span><a href="#Dimensions" data-toc-modified-id="Dimensions-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Dimensions</a></span></li></ul></li><li><span><a href="#Summary-Stats" data-toc-modified-id="Summary-Stats-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Summary Stats</a></span><ul class="toc-item"><li><span><a href="#Measures-of-Central-Tendency" data-toc-modified-id="Measures-of-Central-Tendency-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Measures of Central Tendency</a></span><ul class="toc-item"><li><span><a href="#mean" data-toc-modified-id="mean-2.1.1"><span class="toc-item-num">2.1.1&nbsp;&nbsp;</span>mean</a></span></li><li><span><a href="#median" data-toc-modified-id="median-2.1.2"><span class="toc-item-num">2.1.2&nbsp;&nbsp;</span>median</a></span></li></ul></li><li><span><a href="#Measures-of-Dispersion" data-toc-modified-id="Measures-of-Dispersion-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Measures of Dispersion</a></span><ul class="toc-item"><li><span><a href="#standard-deviation" data-toc-modified-id="standard-deviation-2.2.1"><span class="toc-item-num">2.2.1&nbsp;&nbsp;</span>standard deviation</a></span></li><li><span><a href="#variance" data-toc-modified-id="variance-2.2.2"><span class="toc-item-num">2.2.2&nbsp;&nbsp;</span>variance</a></span></li></ul></li><li><span><a href="#Other" data-toc-modified-id="Other-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Other</a></span><ul class="toc-item"><li><span><a href="#min-and-max" data-toc-modified-id="min-and-max-2.3.1"><span class="toc-item-num">2.3.1&nbsp;&nbsp;</span>min and max</a></span></li><li><span><a href="#sum,-prod-and-cumsum,-cumprod" data-toc-modified-id="sum,-prod-and-cumsum,-cumprod-2.3.2"><span class="toc-item-num">2.3.2&nbsp;&nbsp;</span>sum, prod and cumsum, cumprod</a></span></li></ul></li></ul></li></ul></div>

# Inspect

<div class="alert alert-success alertsuccess" style="margin-top: 20px">

## Objetivos de aprendizagem  <a class="tocSkip">
    
No final deste notebook o aluno deverá saber inspecionar os dados.


## Learning Objectives  <a class="tocSkip">
       
When concluding this notebook, the student should know how to inspect numerical data. </div>

<div class="alert alert-success alertsuccess" style="margin-top: 20px">

## Sumário  <a class="tocSkip">
### Inspecionamento de dados<a class="tocSkip">

Introdução dos alunos a inspeção de dados
- informação básica (a estrutura ndarray, dimensões)
- estatísticas sumárias (medidas de tendência central e de dispersão)
    
## Class Summary  <a class="tocSkip">
### Data Inspection <a class="tocSkip">
Introducing students to data inspection
- basic information (ndarray structure, dimensions)
- summary stats (measures of central tendency; measures of dispersion)

</div>

## Basic Information

### ndarray structure

Para verificar o tipo de dados (ndarray) podemos recorrer ao type:

In [1]:
import numpy as np

a = np.array([0,1,2,3])
type(a)

numpy.ndarray

### array type

Para verificar o tipo de dados do array:

In [2]:
a.dtype

dtype('int32')

Obteremos um erro se por exemplo tentarmos atribuir um tipo errado a um elemento do array:

In [3]:
a[0] = "hello"

ValueError: invalid literal for int() with base 10: 'hello'

### Dimensions

A diferença entre os objetos prende-se apenas com as suas dimensões (uni-dimensional, bi-dimensional, etc), estrutura, e número de elementos. A dimensão pode ser obtida a partir da função ndim, a forma a partir da shape, e o número de elementos a partir da função size.

In [4]:
print(np.ndim(a))
print(np.shape(a))
print(np.size(a))

1
(4,)
4


<img src="https://www.di.ubi.pt/~rcampos/assets/img_tutorials/DataScience/NumpyShape1.jpg" width="300" height="300" align="center"/>

<img src="https://www.di.ubi.pt/~rcampos/assets/img_tutorials/DataScience/NumpyShape2.jpg" width="300" height="300" align="center"/>

<img src="https://www.di.ubi.pt/~rcampos/assets/img_tutorials/DataScience/NumpyShape3.jpg" width="300" height="300" align="center"/>

## Summary Stats

Vamos ler de novo os dados do ficheiro das temperaturas:

In [16]:
data = np.loadtxt('C:/Users/rene_/01-Python/ubi-master-computer-engineering/14479-DS/Aula-06/data/stockholm_td_adj.dat')

<hr>

### Measures of Central Tendency

#### mean

In [18]:
# média dos valores das temperaturas de Estocolmo ao longo dos últimos 200 anos registados na coluna com indíce 3
np.mean(data[:,3])

6.197109684751585

<hr>

#### median

In [19]:
np.median(data[:,3])

5.7

<hr>

### Measures of Dispersion

#### standard deviation

O desvio padrão é uma medida que expressa o grau de dispersão de um conjunto de dados. Ou seja, o desvio padrão indica o quanto um conjunto de dados é uniforme. Quanto mais próximo de 0 for o desvio padrão, mais homogêneo são os dados.

In [20]:
np.std(data[:,3])

8.282271621340573

#### variance

Variância é uma medida de dispersão e é usada também para expressar o quanto um conjunto de dados se desvia da média.

In [21]:
np.var(data[:,3])

68.59602320966341

<hr>

### Other

#### min and max

In [22]:
# lowest daily average temperature
data[:,3].min()

-25.8

In [23]:
# highest daily average temperature
data[:,3].max()

28.3

No caso de uma matriz:

In [24]:
import numpy as np
m = np.random.rand(3,3)
m

array([[0.67875977, 0.4480196 , 0.11974369],
       [0.8233697 , 0.65462578, 0.8697659 ],
       [0.21446058, 0.8214325 , 0.88124062]])

No caso dos arrays multidimensionais é necessário ter em atenção aos eixos. Tal como os sistemas de coordenadas, arrays numpy também têm eixos. 

- o eixo 0 é o eixo que corre verticalmente ao longo das linhas.
- o eixo 1 é o eixo que corre horizontamente ao longo das colunas.

<img src="https://www.di.ubi.pt/~rcampos/assets/img_tutorials/DataScience/NumpyAxis1.jpg" width="300" height="300" align="center"/>

In [25]:
#Cálculo do máximo global
m.max()

0.8812406164265726

In [26]:
# max in each column
m.max(axis=0)

array([0.8233697 , 0.8214325 , 0.88124062])

In [28]:
# max in each row
m.max(axis=1)

array([0.67875977, 0.8697659 , 0.88124062])

<hr>

#### sum, prod and cumsum, cumprod

In [29]:
a1 = np.array([1,2,3,4])
sum(a1)

10

In [17]:
np.cumsum(a1)

array([ 1,  3,  6, 10])

In [18]:
np.prod(a1)

24

In [19]:
np.cumprod(a1)

array([ 1,  2,  6, 24])